<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select city_U7qQSI</name>
   <tag></tag>
   <elementGuidId>5c7e33f9-0828-4b4e-b449-879433f2d82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div[2]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.U7qQSI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.U7qQSI</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1634eb58-7e05-444c-bc51-e73a30eade53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>U7qQSI</value>
      <webElementGuid>b071ab20-16d1-4ab8-b986-43ace2e68e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;krHvwW&quot;]/div[@class=&quot;gB4Uk5 J+HqMZ&quot;]/div[@class=&quot;Ja1j8k&quot;]/div[@class=&quot;RbF1Du O3QvBr&quot;]/div[@class=&quot;U7qQSI&quot;]</value>
      <webElementGuid>3d1d2a7f-6ef5-4e45-bd3d-3adf7ea5af44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div[2]/div[3]/div</value>
      <webElementGuid>cabf7a69-292f-47ce-a97a-625b6040d591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>ead4fe06-99f5-42ca-a282-aee080007aed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
